# Generated by Django 3.2.5 on 2021-07-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('ident', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude_deg', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude_deg', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('elevation_ft', models.CharField(blank=True, max_length=10, null=True)),
                ('continent', models.CharField(blank=True, max_length=10, null=True)),
                ('iso_country', models.CharField(blank=True, max_length=10, null=True)),
                ('iso_region', models.CharField(blank=True, max_length=10, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_service', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_code', models.CharField(blank=True, max_length=10, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=10, null=True)),
                ('local_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
