# Generated by Django 3.2.5 on 2021-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviationapp', '0004_auto_20210730_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airports',
            name='ids',
        ),
        migrations.AlterField(
            model_name='airports',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
