# Generated by Django 3.2.5 on 2021-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviationapp', '0005_auto_20210730_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
